version: '3'
services:
  PartyA-node:
    container_name: missionmars-network-PartyA
    image: engineering-docker.software.r3.com/corda-dev:5.0.0-devpreview-rc03
    command:
    - corda-dev-network-agent
    - node
    - missionmars-network-PartyA
    - http://missionmars-network-bootstrapper:8080/
    networks:
    - missionmars-network
    depends_on:
    - bootstrapper
    ports:
    - 12111:10000
    - 12112:8888
    - 12113:9000
    - 12114:12114
    labels:
      type: corda
      x500: C=GB, L=London, O=Mars Express, OU=LLC
    environment:
      CORDA_DEBUG_PORT: '12114'
    volumes:
    - source: /Users/peterli/.corda/missionmars-network/docker_compose/tmp/PartyA
      target: /opt/nodes/
      type: bind
  PartyB-node:
    container_name: missionmars-network-PartyB
    image: engineering-docker.software.r3.com/corda-dev:5.0.0-devpreview-rc03
    command:
    - corda-dev-network-agent
    - node
    - missionmars-network-PartyB
    - http://missionmars-network-bootstrapper:8080/
    networks:
    - missionmars-network
    depends_on:
    - bootstrapper
    ports:
    - 12115:10000
    - 12116:8888
    - 12117:9000
    labels:
      type: corda
      x500: C=US, L=New York, O=Peter, OU=INC
    environment: &id001 {
      }
    volumes:
    - source: /Users/peterli/.corda/missionmars-network/docker_compose/tmp/PartyB
      target: /opt/nodes/
      type: bind
  notary-node:
    container_name: missionmars-network-notary
    image: engineering-docker.software.r3.com/corda-dev:5.0.0-devpreview-rc03
    command:
    - corda-dev-network-agent
    - node
    - missionmars-network-notary
    - http://missionmars-network-bootstrapper:8080/
    networks:
    - missionmars-network
    depends_on:
    - bootstrapper
    ports:
    - 12118:10000
    - 12119:8888
    - 12120:9000
    labels:
      type: corda
      x500: O=notary, L=London, C=GB
      notary: 'true'
    environment: *id001
    volumes:
    - source: /Users/peterli/.corda/missionmars-network/docker_compose/tmp/notary
      target: /opt/nodes/
      type: bind
  bootstrapper:
    container_name: missionmars-network-bootstrapper
    image: engineering-docker.software.r3.com/corda-dev:5.0.0-devpreview-rc03
    networks:
    - missionmars-network
    command:
    - python3
    - -u
    - scaffold.py
    - --node
    - missionmars-network-PartyA
    - |-
      {"legal_name": "C=GB, L=London, O=Mars Express, OU=LLC", "rpcUsers": [{"user": "user1",
            "password": "test", "permissions": ["ALL"]}, {"user": "angelenos", "password": "password",
            "permissions": ["ALL"]}]}
    - --node
    - missionmars-network-PartyB
    - |-
      {"legal_name": "C=US, L=New York, O=Peter, OU=INC", "rpcUsers": [{"user": "user1",
            "password": "test", "permissions": ["ALL"]}, {"user": "londoner", "password": "password",
            "permissions": ["ALL"]}]}
    - --notary
    - missionmars-network-notary
    - |-
      {"legal_name": "O=notary, L=London, C=GB", "rpcUsers": [{"user": "user1", "password": "test",
            "permissions": ["ALL"]}]}
    environment:
      NODE_BOOTSTRAPPER_TIMEOUT: '20'
    labels:
      type: bootstrapper
    volumes:
    - source: /Users/peterli/.corda/missionmars-network/docker_compose/tmp/bootstrapper
      target: /opt/nodes/
      type: bind
networks:
  missionmars-network:
    name: missionmars-network

